global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@identity-system.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
    
# Identity System specific alert configuration
- name: 'identity-system-alerts'
  webhook_configs:
  - url: 'http://query-service:8080/api/v1/alerts/webhook'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']