extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
  
  zipkin:
    endpoint: 0.0.0.0:9411
  
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  memory_limiter:
    limit_mib: 1000
    spike_limit_mib: 200
    check_interval: 5s
  
  resource:
    attributes:
      - key: service.namespace
        value: identity-system
        action: insert
      - key: deployment.environment
        from_attribute: deployment.environment
        action: upsert
      - key: service.instance.id
        from_attribute: service.instance.id
        action: upsert

  # Add correlation context
  groupbytrace:
    wait_duration: 10s
    num_traces: 100

exporters:
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/?database=signoz_metrics
    username: signoz
    password: signoz_password
  
  clickhousetraceswrite:
    endpoint: tcp://clickhouse:9000/?database=signoz_traces
    username: signoz
    password: signoz_password
  
  clickhouselogswrite:
    endpoint: tcp://clickhouse:9000/?database=signoz_logs
    username: signoz
    password: signoz_password
  
  # For debugging - can be disabled in production
  logging:
    loglevel: debug

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [memory_limiter, batch, resource, groupbytrace]
      exporters: [clickhousetraceswrite]
    
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [clickhousemetricswrite]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [clickhouselogswrite]